# Generated by Django 5.1.2 on 2024-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_notes2_2_link_alter_pastpaper1_1_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='firstYear_rep',
            field=models.CharField(default='8Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='fourthYear_rep',
            field=models.CharField(default='8Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='phone1',
            field=models.CharField(default='113631232', max_length=9),
        ),
        migrations.AddField(
            model_name='course',
            name='phone2',
            field=models.CharField(default='113631232', max_length=9),
        ),
        migrations.AddField(
            model_name='course',
            name='phone3',
            field=models.CharField(default='113631232', max_length=9),
        ),
        migrations.AddField(
            model_name='course',
            name='phone4',
            field=models.CharField(default='113631232', max_length=9),
        ),
        migrations.AddField(
            model_name='course',
            name='secondYear_rep',
            field=models.CharField(default='8Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='thirdYear_rep',
            field=models.CharField(default='8Tech', max_length=100),
        ),
    ]
